package net.mbmedia.drunkmerlin.Challenges;

public class StandardFragenSet {

    public static final int minAnzahl = 700;


    public StandardFragenSet(){

    }

    public static String[] getStandardFragen(){
        return standardfragen;
    }

    private static String[] standardfragen = {
            "während dem Sex mit Haushaltsgegenständen experimentiert.",
            "mehr als 3 Tage im Krankenhaus verbracht.",
            "im Schlaf gesabbert.",
            "mehr als eine Woche im Krankenhaus verbracht.",
            "ein gebrochenes Herz gehabt.",
            "meinem Partner das Frühstück ans Bett gebracht.",
            "gehofft, mein Partner wäre etwas offener in Sachen Sex.",
            "mit meinem Partner geschlafen, nur weil er es wollte.",
            "ein Date gehabt, nur um einer anderen Person wehzutun.",
            "was mit einem Austauschstudierenden gehabt.",
            "einer Person gesagt, dass ich sie liebe.",
            "unter der Dusche gesungen.",
            "eine Krankheit vorgetäuscht.",
            "nach Nacktfotos einer bestimmten Person im Internet gesucht.",
            "jemanden aus Wut lausthals angeschrien.",
            "eine Bong geraucht.",
            "jemanden vom gleichen Geschlecht auf sexuelle Weise attraktiv gefunden.",
            "jemanden ausgezogen, während er schlief.",
            "eine Straftat begangen.",
            "ohne Verhütung mit einer fremden Person geschlafen.",
            "ein Konzert besucht.",
            "meinen Partner mit dem Namen eines Ex-Partners angesprochen.",
            "jemanden beim Pornos schauen erwischt.",
            "ein Buch für die Schule komplett durchgelesen.",
            "mehr als 10 verschiedene Sexstellungen ausprobiert.",
            "im Schlaf geredet.",
            "einer fremden Person auf der Straße geholfen.",
            "mit einer elektrischen Zahnbürste onaniert.",
            "versucht an das Passwort einer anderen Person zu kommen.",
            "einen Sex-Ratgeber gelesen.",
            "aus Eifersucht eine Szene gemacht.",
            "eine Affäre mit einer verheirateten Person gehabt.",
            "etwas aus einem Hotelzimmer mitgehen lassen.",
            "etwas aus dem Bauchnabel einer anderen Person getrunken.",
            "einen Geschlechtsakt gehabt, der länger als drei Stunden gedauert hat.",
            "nach einem Horrorfilm das ganze Haus abgesucht.",
            "einen ganzen Tag lang geweint.",
            "einen Strafzettel bekommen.",
            "Unterwäsche vom anderen Geschlecht getragen.",
            "nach einem Besuch beim Friseur geweint.",
            "einen besonderen Menschen verloren.",
            "ein Auto gefahren, mit dem ich nicht hätte fahren dürfen.",
            "vergessen meine Pille zu nehmen.",
            "Sex mit einem Vorgesetzen oder Lehrer gehabt.",
            "jemandem gesagt, dass ich seinen Körper schön finde.",
            "auf einer Party geweint.",
            "etwas geschluckt, das ich nie wieder freiwillig schlucken würde.",
            "für jemanden gekocht.",
            "mich in meinen besten Freund verliebt.",
            "mit insgesamt mehr als 15 Leuten in meinem Leben geschlafen.",
            "beim Zahnarzt geweint.",
            "eine Panne gehabt, weil ich vergessen habe zu tanken.",
            "über meinen Ex gedacht: Wie konnte ich nur mit diesem Menschen zusammen sein?",
            "Wahrheit oder Pflicht gespielt.",
            "ein anderes Fahrzeug beschädigt und Fahrerflucht begangen.",
            "jemanden nach seiner Telefonnummer gefragt und danach nie angerufen.",
            "einen Sextraum gehabt.",
            "halb nackt die Türe für eine fremde Person geöffnet (z.B. Postbote).",
            "per SMS mit jemandem Schluss gemacht.",
            "einen Dildo in meinen Händen gehalten.",
            "mehr als drei Orgasmen an einem Tag gehabt.",
            "ein Angebot für Sex abgelehnt.",
            "an den Ohrläppchen meines Partners geleckt.",
            "einem befreundetesn Pärchen einen Vierer angeboten.",
            "bei einem Doppeldate mitgemacht, nur damit ein Freund mit ihrem Schwarm ausgehen kann.",
            "einen Vorschlag für die App abgeschickt.",
            "im Auto ganz laut die Musik aufgedreht und mitgesungen.",
            "Sex auf einem Trampolin gehabt.",
            "jemanden kennengelernt, der schon einmal im Gefängnis sitzen musste.",
            "bei diesem Spiel als einziger trinken müssen.",
            "in einer Woche mindestens einmal täglich Sex gehabt.",
            "den Notruf gewählt.",
            "mit einem Kuscheltier geredet.",
            "während eines Dates eine Ausrede benutzt, um das Treffen frühzeitig zu beenden.",
            "ein Mädchen geküsst.",
            "solche Aggressionen gehabt, dass ich jemanden hätte töten können.",
            "einen Tampon in der Nase stecken gehabt.",
            "meine Eltern/Geschwister nackt gesehen.",
            "meinen Chef angeschrien.",
            "im Vollrausch vergessen, wo ich wohne.",
            "mit einem fremden Auto einen Unfall gebaut.",
            "Rosen geschenkt bekommen.",
            "so viel getrunken, dass ich beim Sex eingeschlafen bin.",
            "eine Sex-Beziehung geführt.",
            "etwas verloren, weil ich so betrunken war.",
            "mehr als 10 Minuten auf der Toilette verbracht.",
            "einen Schwangerschaftstest gemacht.",
            "jemanden gedated, der eigenartig war.",
            "völlig nackt geschlafen.",
            "Sexspielzeug von anderen Leuten gefunden.",
            "Sex im Freien gehabt und bin dabei erwischt worden.",
            "so getan als hätte ich kein Geld mehr, weil ich für eine bestimmte Sache kein Geld ausgeben wollte.",
            "gesagt bekommen, ich sei zu schnell gekommen.",
            "Sex in der Öffentlichkeit gehabt (z.B. öffentliche Toilette).",
            "Gefühle für eine Person aus meiner Klasse gehabt.",
            "Sex in einem Auto, Zug oder Bus gehabt.",
            "Liebeskugeln verwendet.",
            "mit jemandem geschlafen, um an jemand anderen heranzukommen.",
            "Urlaub mit Freunden gemacht.",
            "mit meinen Eltern über meine Sexualität gesprochen.",
            "mehr als 5 mal an einem Tag masturbiert.",
            "Sexspielzeuge gemeinsam mit meinem Partner benutzt.",
            "gewünscht die Eltern eines Freundes wären meine.",
            "etwas auf der Arbeit geklaut.",
            "eine erotische Massage gegeben oder erhalten.",
            "jemanden mit sehr unangenehmen Mundgeruch geküsst.",
            "mit einem Ex-Partner geschlafen.",
            "in der Uni / Schule Sex gehabt.",
            "für jemanden gestrippt.",
            "meine Zähne mit einer fremden Zahnbürste geputzt.",
            "etwas geklaut.",
            "meinen Intimbereich rasiert.",
            "Lebensmittel beim Sex benutzt.",
            "alleine zuhause so viel getrunken, dass ich sturz betrunken war.",
            "bei diesem Spiel etwas neues über einen Mitspieler erfahren, was ich nicht von ihm erwartet hatte.",
            "Sexspielzeug gekauft.",
            "künstliches Gleitmittel benutzt.",
            "einen Liebesakt gehabt, der länger als eine Stunde gedauert hat.",
            "unter einer falschen Identität versucht einen Bekannten/Freund über das Internet zu kontaktieren.",
            "meine Eltern belogen.",
            "Sex gehabt, ohne vorher die Schuhe auszuziehen.",
            "eine Mutprobe mitgemacht.",
            "versucht jemandem den Partner auszuspannen.",
            "für meinen besten Freund/meine beste Freundin gelogen.",
            "ein Bild verschickt, für das ich mich im Nachhinein schäme.",
            "einen Lehrer/Vorgesetzten nackt vorgestellt.",
            "Analsex gehabt.",
            "mehr als eine halbe Stunde im Internet nach einer bestimmten Person (nicht ich selbst) recherchiert.",
            "an einem Casting teilgenommen.",
            "Sex im Hotel gehabt.",
            "meinen Partner betrogen.",
            "in der Öffentlichkeit gekotzt.",
            "ein Kompliment über meine Geschlechtsteile bekommen.",
            "den Sex “ausfallen” lassen, weil kein Verhütungsmittel zur Hand war.",
            "meine Eltern beim Sex erwischt.",
            "etwas im Internet bestellt, weil ich mich nicht getraut habe, es im Laden zu kaufen.",
            "erotische Bilder oder Kalender aufgehängt.",
            "während dem Telefonieren masturbiert.",
            "ein Tier auf den Mund geküsst.",
            "meinem Partner mehr als 4 Orgasmen während eines Liebesaktes bereitet.",
            "im Club rumgemacht.",
            "versucht anstößige Geheimnisse über einen Freund herauszubekommen.",
            "mit jemandem aus meinem Freundeskreis Sex gehabt.",
            "für eine deutlich ältere Person geschwärmt.",
            "einer religiösen Sekte angehört.",
            "an einem anderen Ort als im Bett Sex gehabt.",
            "einen Partner gehabt, bei dem ich Angst hatte, ihn meinem Eltern vorzustellen.",
            "einen Fan-Brief an einen Promi geschrieben.",
            "einen Partner gehabt dessen Eltern mich nicht leiden konnten.",
            "eine erotische SMS / E-Mail / Nachricht versendet.",
            "vergessen, dass Feiertag/Wochenende war und bin zur Arbeit/Schule erschienen.",
            "eine Sex-Beziehung mit einer Person gehabt mit der ich nicht zusammen war.",
            "jemanden beim Sex beobachtet.",
            "überlegt in einen SM- / Bondage Club zu gehen.",
            "meinen Ausweis verloren.",
            "Geld gefunden und es einfach behalten.",
            "etwas im Wert von über 500€ kaputt gemacht oder verlegt.",
            "jemanden geküsst und es danach bereut.",
            "auf einer Hochzeit gedacht, dass diese Ehe nicht lange halten wird.",
            "das Kamasutra “gelesen”.",
            "Sex an einem anderen Ort als im Bett gehabt.",
            "bei einem Dreier mitgemacht.",
            "ein Möbelstück beim Sex kaputt gemacht.",
            "so viel getrunken, dass ich mich an einiges nicht mehr erinnern kann.",
            "den Wunsch gehabt, in eine andere Stadt zu ziehen.",
            "vor dem Spiegel getanzt.",
            "über einen Freund gedacht, dass seine Eltern bei der Erziehung versagt haben.",
            "das Herz eines Mitmenschen gebrochen.",
            "Sex in der Küche gehabt.",
            "mehr als 100€ für eine Taxifahrt ausgegeben.",
            "auf der Arbeit Alkohol getrunken.",
            "einen Fallschirmsprung gemacht.",
            "eine ganze Chilischote gegessen.",
            "eine Kontaktanzeige aufgegeben oder auf eine geantwortet.",
            "nackt in einem See / Meer gebadet.",
            "einen erotischen Traum gehabt, den ich niemals in die Tat umsetzen würde.",
            "mit jemandem Schluss gemacht.",
            "jemandem einfach so auf den Hintern gehauen (nicht mein Freund/meine Freundin).",
            "so getan als würde ich vor einem Millionenpublikum stehen und singen.",
            "einen peinlichen Rechtschreibfehler gemacht.",
            "vor einer größeren Gruppe “blank” gezogen.",
            "mein Flugzeug verpasst.",
            "mehr als 3 Stellungen bei einem Akt ausprobiert.",
            "das Bedürfnis gehabt einen Menschen zu töten.",
            "ein One-Night-Stand gehabt.",
            "Fotos / Videos während dem Sex gemacht.",
            "beim Aufwachen nicht gewusst wo ich bin.",
            "einen Brief eingeworfen und versucht ihn wieder zu bekommen.",
            "in einem Club mit mehr als 3 Personen rumgemacht.",
            "so heftig gelacht, dass ich pinkeln musste.",
            "vor 13 Uhr so viel getrunken, dass ich sturz besoffen war.",
            "eine Beziehung gehabt, obwohl ich genau wusste, dass ich mit dieser Person nicht enden werde.",
            "ein Referat aus dem Internet ausgedruckt und in der Schule / Uni vorgetragen.",
            "ein Tier umgebracht.",
            "Massageöl benutzt.",
            "gemeinsam mit einer anderen Person geduscht oder gebadet.",
            "eine falsche Identität im Internet benutzt.",
            "beim Masturbieren jemanden zuschauen lassen.",
            "jemanden in einer zweideutigen Situation erwischt.",
            "Sex auf einem Baum gehabt.",
            "mit einer deutlich jüngeren Person geschlafen.",
            "mit jemandem geschlafen ohne zu verhüten.",
            "ein Möbelstück selbst aufgebaut.",
            "darüber nachgedacht, eine Beziehung zu beenden.",
            "Sex während einer Party gehabt.",
            "ein Geschenk vergessen.",
            "falsche Angaben gemacht bei der Frage mit wie vielen Leuten ich geschlafen habe.",
            "meine Hausaufgaben abgeschrieben.",
            "einen Liebesbrief geschrieben.",
            "mein Alter verleugnet, nur um jemanden näher kennenzulernen.",
            "gesagt die Verbindung sei schlecht, nur um ein Telefonat zu beendet.",
            "in einem Club Sex gehabt.",
            "ein übles Gerücht über jemanden in die Welt gesetzt.",
            "nackt vor dem Computer gesessen.",
            "einen Penis in der Hand gehalten.",
            "Disneyland besucht.",
            "etwas beim Sex getan, wobei ich mich total blamiert habe.",
            "einen Tanga getragen.",
            "heimlich meine Nachbarn beobachtet.",
            "ein Buch gelesen, das mich richtig angeturnt hat (z.B. Fifty Shades of Grey).",
            "eine Beziehung gehabt, die ich im Nachhinein bereue.",
            "vor einer Menschenmenge Karaoke gesungen.",
            "ein Haustier gehabt.",
            "mehr als 200€ an einem Abend ausgegeben.",
            "jemanden aufgrund seines Aussehens ausgelacht.",
            "nach dem Aufwachen keine Ahnung gehabt, was am Vorabend passiert ist.",
            "eine Stellung aus dem Kamasutra ausprobiert.",
            "mein Handy verloren.",
            "jemandem zum Geschlechtsverkehr gezwungen.",
            "ein Selfie gemacht.",
            "etwas auf jemand anderen geschoben, das in Wirklichkeit ich gemacht habe.",
            "wo anders als zuhause masturbiert.",
            "in die Dusche gepinkelt.",
            "zugeben müssen, dass ich noch Jungfrau bin.",
            "Sex in einem Fahrstuhl gehabt.",
            "Eifersucht verspürt, als ich hörte, dass ein Prominenter für den ich schwärme, vergeben ist.",
            "ein Kleidungsstück gekauft, getragen und am nächsten Tag zurück gebracht.",
            "eine Frage bei einem Trinkspiel falsch beantwortet.",
            "Cybersex ausprobiert.",
            "einen Popel gegessen.",
            "einen Vorgesetzten/Lehrer/Chef so laut beleidigt, dass er es gehört hat.",
            "in einem öffentlichen Verkehrsmitteln mit jemandem rumgeknutscht.",
            "einen erotischen Roman gelesen.",
            "wegen eines Katers auf der Arbeit kotzen müssen.",
            "bei einer Klausur abgeschrieben.",
            "den Namen eines Ex-Partners vergessen.",
            "eine durch Geschlechtsverkehr übertragbare Krankheit gehabt.",
            "versucht betrunken auf einen Baum zu klettern.",
            "etwas Sexuelles im Internet gesucht.",
            "versucht etwas zu kaufen für das ich mich geschämt habe und bin daher unauffällig durch die Regale geschlendert um nicht aufzufallen.",
            "einen Bungee-Sprung gemacht.",
            "sexuelle Wünsche / Fantasien gehabt, die ich mich nicht getraut habe mit meinem Partner zu besprechen.",
            "das Gefühl gehabt mit meinem Körper komplett zufrieden zu sein.",
            "ein sehr peinliches Rollenspiel mitgemacht.",
            "geraucht.",
            "jemanden entjungfert.",
            "so viel getrunken, dass ich nur mit fremder Hilfe nach Hause gekommen bin.",
            "einen erfolgreich abgenommen.",
            "etwas besonders Ekliges gegessen.",
            "darauf gewartet, dass mich jemand anspricht, weil ich mich selbst nicht getraut habe.",
            "etwas Unanständiges im Kino getan.",
            "versaute Sachen gesagt um jemanden scharf zu machen.",
            "gegen das andere Geschlecht bei einem Trinkspiel gewonnen.",
            "auf einer Party mit jemandem rumgemacht.",
            "Ananassaft getrunken, damit das Sperma besser schmeckt.",
            "vor einem Flug getrunken um meine Nerven zu beruhigen.",
            "bei einem Film geweint.",
            "einen Orgasmus vorgetäuscht.",
            "Sex mit einem Arbeitskollegen gehabt.",
            "ein Onlinespiel gespielt.",
            "erotische Unterwäsche getragen.",
            "gewünscht, ich könnte einfach wieder ein kleines Kind sein.",
            "ein perverses Bild über Snapchat verschickt.",
            "Geschlechtsverkehr im Flugzeug gehabt.",
            "mich selbst in den Schlaf geweint.",
            "Fantasien gehabt, in denen ich gefoltert oder gefesselt wurde.",
            "meine Eltern gefragt, wo ich genau gezeugt wurde.",
            "vegan gelebt.",
            "Kondome mit Geschmack benutzt.",
            "den Namen einer falschen Person während dem Geschlechtsverkehr ausgesprochen.",
            "jemanden gleichzeitig geliebt und gehasst.",
            "den Freund einer meiner Freundeninnen geliebt.",
            "an einem FKK Strand gebadet.",
            "über eine 5 Stunden durchgehend mit jemandem telefoniert.",
            "einen Tag im Pyjama verbracht.",
            "Lust gehabt mit einem der anwesenden Spielern zu schlafen.",
            "beim Rummachen mit meinem Partner an jemand anderen gedacht.",
            "mich so sehr blamiert, dass ich mich bis heute dafür schäme.",
            "Sex gehabt.",
            "mich selbst gestreichelt und mir vorgestellt es sei jemand anderes.",
            "an einer Ferienfreizeit teilgenommen.",
            "meinem Partner erotische Texte geschrieben um ihn anzumachen.",
            "einen Partner gehabt, der in Sachen Sex deutlich offener war als ich.",
            "einem Partner von Sexerlebnissen mit meinem Ex erzählt.",
            "eine Fotokopie von meinem Gesicht gemacht.",
            "so getan als hätte ich eine Nachricht nicht gelesen, weil ich nicht darauf antworten wollte.",
            "jemanden heimlich beobachtet.",
            "beim Sex meinem Partner die Dominanz überlassen.",
            "bezüglich meines Gewichts um bis zu 20kg gelogen.",
            "mit jemandem geschlafen, der jünger als 16 Jahre alt war.",
            "jemanden geküsst, ohne seinen Namen zu wissen.",
            "meinen bzw. den Penis meines Partner mit dem Lineal vermessen.",
            "in den persönlichen Dateien auf einem fremden Computer gestöbert.",
            "bei diesem Spiel als einzige Person nicht getrunken.",
            "so viel Angst gehabt, dass ich am ganzen Körper gezittert habe.",
            "wegen Sex Muskelkater gehabt.",
            "das Etikett eines Kleidungsstücks entfernt, weil es eine Billigmarke war.",
            "Bilder meines Ex-Partners ins Internet gestellt.",
            "den Multiplayer ausprobiert.",
            "“Ich liebe dich” gesagt, obwohl ich es nicht so meinte.",
            "darauf gewartet, dass endlich jemand vorschlägt nackt weiterzuspielen.",
            "jemanden über eine Datingseite im Internet kennengelernt.",
            "mit anstößigen Gefälligkeiten für etwas bezahlt.",
            "Sex vor anderen Menschen gehabt.",
            "etwas anderes als Klopapier benutzt.",
            "versucht mit meinem Partner einen Porno nachzuspielen.",
            "besoffen ein Geheimnis ausgeplaudert.",
            "noch beim ersten Date mit jemandem geschlafen.",
            "Sex auf dem Küchentisch gehabt.",
            "Sex in allen Räumen meiner Wohnung gehabt.",
            "eine Person geküsst, die das gleiche Geschlecht hat wie ich.",
            "ein Date mit dem Ex einer Freundin/eines Freundes gehabt.",
            "mit jemanden rumgemacht, der in einer festen Beziehung war.",
            "eine Erektion gesehen.",
            "darüber nachgedacht ein sexuelles Rollenspiel zu machen.",
            "so viel Angst bei einem Horrorfilm gehabt, dass ich laut geschrien habe.",
            "Fesselspielchen gemacht.",
            "mir einen meiner jetzigen Mitspieler nackt vorgestellt.",
            "einen Rausschmiss in einem Club bekommen.",
            "um Sex gebettelt.",
            "in einem Flugzeug gesessen.",
            "überlegt, mir ein Tattoo stechen zu lassen.",
            "Sex an einem öffentlichen Ort gehabt.",
            "etwas nur aus Höflichkeit gegessen, obwohl es in Wahrheit nicht schmeckte.",
            "mit einer Person geflirtet, obwohl ich wusste, dass die Person vergeben ist.",
            "einen ganzen Arbeitstag im Internet verbracht.",
            "Reizwäsche getragen.",
            "Sex ohne Verhütungsmittel gehabt.",
            "mit einer deutlich älteren Person geschlafen.",
            "mit jemandem geschlafen, der auch mit meinem besten Freund/meiner besten Freunden geschlafen hat.",
            "drei Nächte am Stück durchgefeiert.",
            "eine Schlägerei mit einem Türsteher gehabt.",
            "eine Party besucht mit der Absicht, heute bloß nicht alleine nach Hause zu gehen.",
            "Sperma geschluckt.",
            "meinen besten Freund geküsst.",
            "die Klamotten von jemand anderem versteckt.",
            "mit meinem Partner offen über Masturbation gesprochen.",
            "einen Schwangerschaftstest gekauft.",
            "in den vergangenen 2 Jahren 2 Wochen ohne einen einzigen Orgasmus verbracht.",
            "von meinen Eltern Geld geklaut.",
            "Sex in einer Umkleidekabine gehabt.",
            "einen Film mehr als 15 Mal gesehen.",
            "einen Quickie gehabt.",
            "einen ganzen Tag Computer gespielt.",
            "in einem Kinofilm geschlafen.",
            "beim Sex die Dominanz übernommen.",
            "in einem Raum geschlafen, in dem andere Leute Sex hatten.",
            "in einem Bett mit mehr als einer nackten Person gelegen.",
            "Sex gehabt und ein Freund kam in den Raum.",
            "draußen im Gras geschlafen, weil ich so betrunken war.",
            "mit meinem Partner über alle meine sexuellen Wünsche gesprochen.",
            "Strapse oder Lack und Leder getragen.",
            "nachts nackt gebadet.",
            "ein Strip-Lokal von innen gesehen.",
            "nach dem Sex das Gefühl gehabt nicht richtig befriedigt zu sein.",
            "das Gefühl gehabt, dem biologisch benachteiligtem Geschlecht anzugehören.",
            "versucht, das Passwort eines Anderen zu erraten.",
            "den Wunsch gehabt, unsichtbar zu sein.",
            "eine Person geküsst, die hier im Raum ist.",
            "eine Beziehung mit einer Person gehabt, die ich über das Internet kennengelernt habe.",
            "einen handfesten Streit in der Öffentlichkeit gehabt.",
            "einen Pickel ausgedrückt.",
            "in einem Hotelzimmer den Pornokanal geschaut.",
            "darüber nachgedacht, wie einer der Mitspieler nackt aussieht.",
            "etwas zerstört, nur um mich an jemandem zu rächen.",
            "darüber nachgedacht, was nach dem Tod passieren wird.",
            "eine Kündigung erhalten.",
            "Sex gehabt, bei dem ich nicht zum Orgasmus gekommen bin.",
            "in der Dusche gesungen.",
            "einen Abend ohne Freunde oder Bekannte in einem Club verbracht.",
            "beim Aufwachen gedacht: Wer ist das neben mir?",
            "bei einer Hausparty etwas kaputt gemacht.",
            "vor der Polizei fliehen müssen.",
            "wegen eines Katers die Schule / den Job geschwänzt.",
            "daran gedacht auszuwandern.",
            "mit jemandem geschlafen mit dem ich im Nachhinein lieber nicht geschlafen hätte.",
            "aus einem Teller Wein getrunken.",
            "meine Eltern oder Nachbarn beim Sex gehört.",
            "nackt im Meer/See gebadet.",
            "Strippoker gespielt.",
            "“spontanen” Sex gehabt, obwohl ich bereits spät dran war.",
            "die Eltern einer Freundin/eines Freundes beim Sex gehört.",
            "davon geträumt, ein Charakter aus einem Buch/Film zu sein.",
            "mit dem besten Freund/ der besten Freundin meines Ex Partners was gehabt.",
            "einen Swingerclub von innen gesehen.",
            "wegen eines Sexunfalls ins Krankenhaus gemusst.",
            "bei “Wahrheit oder Pflicht” eine peinliche Pflicht ausführen müssen.",
            "bei einem Film geweint.",
            "darüber nachgedacht mir Sexspielzeug zu kaufen.",
            "etwas gekauft, was ich meinem Partner verschwiegen habe, weil ich wusste, dass er das nicht unterstützt.",
            "Flaschendrehen mit zweideutigen Aufgaben gespielt.",
            "an einem einzigen Tag mehr als 3 mal Sex gehabt.",
            "Sex gehabt, während mich ein Haustier beobachtet hat.",
            "etwas mit jemanden in diesem Raum gehabt.",
            "davon geträumt einen Klassenkameraden / Kommilitonen / Kollegen nackt zu sehen.",
            "ein Kondom in der Hand gehabt.",
            "einen Porno geguckt.",
            "so laut gestöhnt, dass ich Angst hatte, jemand anderes könnte es gehört haben.",
            "mehrere Stunden am Stück ohne Kleidung verbracht.",
            "Geld oder Geschenke für sexuelle Dienste erhalten.",
            "meinen Eltern die Frage beantworten müssen, ob ich noch Jungfrau bin.",
            "zum “Idiotentest” (Führerschein) gehen müssen.",
            "wegen zu viel Alkohol mit einem Fremden rumgemacht.",
            "einen Knochenbruch gehabt.",
            "das Gefühl gehabt, egoistisch zu sein.",
            "etwas Wertvolles kaputt gemacht.",
            "bei Bekannten in den Badezimmerschrank geschaut.",
            "jemandem ein Kompliment über seine Geschlechtsteile gemacht.",
            "eine Frau oral befriedigt.",
            "eine Zigarre geraucht.",
            "im Schwimmbad unter Wasser gefummelt.",
            "das Gefühl gehabt, mich einem Partner voll und ganz hingeben zu wollen.",
            "einen Höhepunkt gehabt.",
            "einen Ladendiebstahl beobachtet.",
            "vor Lachen geweint.",
            "Sex mit mehr als einer Person gleichzeitig gehabt.",
            "im Wald einen geblasen bekommen.",
            "an meinen Nägeln gekaut.",
            "Silikonbrüste berührt.",
            "noch vor dem Frühstück Geschlechtsverkehr gehabt.",
            "als Notfall in einem Krankenwagen gelegen.",
            "zu meinem Exfreund/Exfreundin gesagt: Lass uns Freunde bleiben.",
            "nach dem Feiern ein Blackout gehabt und erinnere mich teilweise an garnichts mehr.",
            "in einem Wutanfall etwas zerstört.",
            "Pornofilme bei mir zuhause versteckt.",
            "eine Fotokopie von meinem Hintern gemacht.",
            "mit jemandem aus einem anderen Land geschlafen.",
            "einen Knutschfleck gehabt.",
            "nach dem Sex masturbiert, weil ich nicht befriedigt war.",
            "Kondome gekauft.",
            "meine(n) Ex in der Stadt verfolgt.",
            "das Geheimnis eines anderen ausgeplaudert (versehentlich oder absichtlich).",
            "von Sex mit einem Dienstleister (Klempner, Krankenschwester,..) geträumt.",
            "so viel getrunken, dass ich mich übergeben musste.",
            "die Sachen meines Partners angezogen.",
            "Gruppensex gehabt.",
            "das Haus verlassen ohne Unterwäsche drunter zu ziehen.",
            "Sex im Bett meiner Eltern gehabt.",
            "beim Sex den Großteil meiner Klamotten angelassen.",
            "Obst oder Gemüse als Sexspielzeug benutzt.",
            "einen Wettbewerb gewonnen.",
            "jemanden beim Masturbieren beobachtet.",
            "mit zwei Leuten am selben Tag geschlafen.",
            "ein Angebot für einen Dreier bekommen.",
            "den Freund / die Freundin meiner besten Freundin / meines besten Freundes geküsst.",
            "jemandem etwas ekliges in den Briefkasten gesteckt.",
            "eine Person in der Öffentlichkeit angesprochen, weil ich sie attraktiv fand.",
            "String-Tangas getragen.",
            "einen meiner Mitspieler nackt gesehen.",
            "jemanden nach seiner Nummer gefragt.",
            "etwas mit einer Person angefangen, die zu diesem Zeitpunkt in einer Beziehung war.",
            "meinen eigenen Namen gegoogelt.",
            "ein ganz besonders außergewöhnliches Sexerlebnis gehabt.",
            "eine Beziehung mit zwei Leuten aus derselben Familie gehabt.",
            "mehrere Orgasmen relativ unmittelbar nacheinander gehabt.",
            "ein hormonelles Verhütungsmittel zu mir genommen.",
            "heimlich den Alkohol meiner Eltern getrunken.",
            "einem Freund/einer Freundin geraten, mit dem Partner/Partnerin Schluss zu machen.",
            "einen Freund verteidigt, auch wenn ich wusste, dass er im Unrecht ist.",
            "heimlich das Getränk eines anderen ausgetrunken.",
            "gesagt, ich sei Single, obwohl ich in einer Beziehung war.",
            "für Sex bezahlt.",
            "einen Prominenten persönlich getroffen.",
            "im Beisein meines Partners geweint.",
            "mit jemandem geflirtet, obwohl ich in einer Beziehung war.",
            "Sex in oder an einem See gehabt.",
            "gehofft, bei dem Spiel nicht als Einziger trinken zu müssen.",
            "im Internet nach Nacktfotos eines Prominenten gesucht.",
            "einen Auftritt im Fernsehen gehabt.",
            "nie getrunken.",
            "einen Korb erhalten, wenn ich mit jemandem ausgehen wollte.",
            "das Jugendamt alarmiert.",
            "für eine deutlich jüngere Person geschwärmt.",
            "eine Zahnspange getragen.",
            "außerhalb von meinem eigenen Zuhause nackt gebadet.",
            "während des Sex gefurzt.",
            "Hilfsmittel bei der Selbstbefriedigung eingesetzt.",
            "eine Freundschaft mit gewissen Vorzügen geführt.",
            "zwei Personen gleichzeitig gedated, weil ich mich nicht entscheiden konnte.",
            "einen Partner gehabt, für den ich mich geschämt habe.",
            "so dringend aufs Klo gemusst, dass ich es nicht geschafft habe.",
            "heimlich meinen Ex gestalked.",
            "ein Wort gegoogelt, weil ich nicht wusste, wie man es schreibt.",
            "Sex auf einer Waschmaschine gehabt.",
            "einen wichtigen Termin verschlafen.",
            "mit jemandem zusammen geduscht.",
            "etwas besser gekonnt als alle meine Freunde.",
            "für erotisches Material bezahlt (Live-Cams, Pornohefte, Videos, etc).",
            "einen Arzttermin vergessen.",
            "tagsüber im Meer Sex gehabt.",
            "geniest und die Hand an jemand anderem abgewischt.",
            "so viel getrunken, dass ich am nächsten Tag um 13 Uhr immernoch betrunken war.",
            "einen Porno gedreht.",
            "mit jemandem geschlafen, an dessen Namen ich mich nicht erinnern konnte.",
            "auf eine andere Person gekotzt.",
            "die Unterwäsche meines Partners ausgeliehen.",
            "so viel getrunken, dass ich den Weg nach Hause nicht mehr gefunden habe.",
            "so getan als würde ich schlafen, nur um nicht mit der Person schlafen zu müssen.",
            "erotische Träume/Phantasien mit jemandem gehabt, den ich eigentlich nicht mag.",
            "einem Partner zuliebe etwas Unangenehmes, Ekliges oder Perverses ausprobiert.",
            "die Anfrage eines Vorgesetzten auf Facebook ignoriert.",
            "einen romantischen Abend mit Kerzen, Rosen usw. verbracht.",
            "mehr als 3 Monate ohne Sex verbracht (letzten 2 Jahre).",
            "mit jemandem über intime Details meines Sexlebens gesprochen (nicht meinem Freund/meiner Freundin).",
            "eine Schwarzfahrt in Kauf genommen, statt mir ein Ticket zu kaufen.",
            "mit jemandem geschlafen, während ich ziemlich betrunken war.",
            "romantische Gefühle für den Partner eines Familienmitglieds gehabt.",
            "andere Leute (Freunde, Kollegen, Bekannte) beim Sex vorgestellt.",
            "eine Stellung “im Stehen” ausprobiert.",
            "in der Sauna andere Leute beobachtet.",
            "überlegt, ob ein Freund/eine Freundin wohl mit mir schlafen wollen würde.",
            "Kängurufleisch gegessen.",
            "während dem Sex mit Lebensmitteln experimentiert.",
            "in den Spiegel geschaut und gedacht: Wow. Sexy!",
            "ein Versprechen gebrochen.",
            "verschlafen.",
            "mein erstes Date im Kino verbracht.",
            "hinter seinem Rücken schlecht über meinen Partner gesprochen.",
            "ein und dieselbe Unterwäsche länger als 5 Tage getragen.",
            "gemeinsam mit einem Partner geduscht oder gebadet.",
            "Krokodilfleisch gegessen.",
            "beim Sex Alltagsprobleme diskutiert.",
            "mit jemandem geschlafen, den ich im Urlaub kennengelernt habe.",
            "von einem Partner ein erotisches Geschenk erhalten.",
            "meine Führerscheinprüfung (Theorie und/oder Praxis) wiederholen müssen.",
            "meinem Intimbereich einen Kosenamen gegeben/geben lassen.",
            "erotische Fotos von mir schießen lassen.",
            "davon geträumt, eine körperliche Beziehung mit einem völlig Fremden zu haben.",
            "auf meine beste/n Freund/in gestanden.",
            "mit jemandem geschlafen, den ich über das Internet kennengelernt habe.",
            "ein Kondom beim Überstreifen kaputt gemacht.",
            "mein Handy in die Toilette fallen lassen.",
            "schlafgewandelt.",
            "mit meinem Partner ohne Verhütung geschlafen.",
            "mit mehr als einer Person gleichzeitig eine sexuelle Beziehung gehabt.",
            "einen Liebesbrief erhalten.",
            "eine Badeessenz für romantische Abende zu zweit benutzt.",
            "auf der Arbeit im Lagerraum/Abstellraum rumgemacht.",
            "einen Partner gehabt, der mich nicht ausreichend sexuell befriedigt hat.",
            "mit jemandem geschlafen, um mich an jemand anderem zu rächen.",
            "während des Sex an eine andere Person gedacht.",
            "den Geburtstag eines Familienangehörigen vergessen.",
            "meinen Partner beim Sex verletzt.",
            "während dem Sex anfangen müssen zu lachen.",
            "einen Tag ohne Unterwäsche verbracht.",
            "meinen Partner mit dem Namen meiner/meines Ex angesprochen.",
            "gesagt bekommen, ich sei gut im Bett.",
            "einen Penis gesehen.",
            "Sex während der Periode gehabt.",
            "ein Partyspiel gespielt, bei dem es auch ums Ausziehen ging.",
            "bei einem Date bezüglich meiner Alters oder meiner Herkunft gelogen.",
            "nach dem Sex Biss- oder Kratzspuren gehabt.",
            "mit meinem Haustier gekuschelt.",
            "Pornohefte gekauft.",
            "mit jemandem geschlafen, obwohl ich eigentlich keine Lust dazu hatte.",
            "etwas aus dem Supermarkt gestohlen.",
            "eine Beziehung mit einer Person verleugnet, mit der ich früher einmal zusammen war.",
            "meinem Partner Anweisungen im Bett gegeben.",
            "bei einer Dating-Website ein Profil erstellt.",
            "Essensreste in meinem Bett gefunden.",
            "bei einer Sex-Hotline angerufen.",
            "essbare Unterwäsche benutzt.",
            "eine Party erst am späten Morgen des Folgetags verlassen.",
            "in eine Flasche gepinkelt.",
            "eine Beziehung beendet, weil der Sex nicht gut genug war.",
            "so getan als wäre ich krank nur um nicht mit jemandem schlafen zu müssen.",
            "mich selbst berührt.",
            "jemanden einen geblasen.",
            "jemandem im Urlaub kennengelernt und weiterhin Kontakt gehalten.",
            "mich selbst für etwas belohnt.",
            "mit jemandem geschlafen, den ich eigentlich nicht attraktiv fand.",
            "eine Entscheidung getroffen, die ich schon unmittelbar danach bereut habe.",
            "mit jemandem aus meinem Büro geschlafen.",
            "während des Sex gähnen müssen.",
            "bei einem einzigen Mal Sex mehr als 5 verschiedene Stellungen ausprobiert.",
            "davon geträumt, an einem außergewöhnlichen Ort Sex zu haben.",
            "Erbrochenes weggemacht.",
            "in einem Parkhaus sexuelle Aktivitäten vollzogen.",
            "die Minibar eines Hotels geleert.",
            "mit meinen Eltern über Verhütung gesprochen.",
            "den Wunsch gehabt, älter zu sein.",
            "Telefonsex gehabt.",
            "ein Liebesgedicht geschrieben.",
            "darüber nachgedacht, wie es wohl wäre, das andere Geschlecht zu haben.",
            "Socken zweimal hintereinander angezogen.",
            "so ein gutes Verhältnis zu meinem Partner/Partnerin gehabt, dass ich die Badezimmertüre offen gelassen habe.",
            "im Wald masturbiert.",
            "“Hilfsmittel” beim Sex eingesetzt (Penisringe, Vibratoren,..).",
            "Verhütungsmittel mitgeführt: “Nur für den Fall”.",
            "so getan die Pille nicht genommen zu haben um dem Sex zu entgehen.",
            "jemanden für mich strippen lassen.",
            "ein erotisches Geschenk für meinen Partner gemacht.",
            "jemandem die Füße geküsst.",
            "eine rote Ampel überfahren.",
            "einen Baum umarmt.",
            "die Schule geschwänzt.",
            "Eifersucht verspürt, weil andere ein spannenderes Liebesleben haben als ich.",
            "etwas eingenommen, um mich sexuell zu stimulieren.",
            "einen Partner betrogen (auch Küssen).",
            "betrunken Nachrichten gesendet, die ich nüchtern bereuet habe.",
            "die Polizei um Hilfe gebeten.",
            "jemanden per Oralsex zum Orgasmus gebracht.",
            "etwas gegessen, obwohl ich wusste, dass das Haltbarkeitsdatum abgelaufen ist.",
            "für erotische Dienstleistungen bezahlt.",
            "nackt oder zumindest halbnackt vor eine Webcam gesessen.",
            "Fingernägel gekaut.",
            "eine E-Mail Adresse angelegt, die ich nutze, wenn ich anonym bleiben will.",
            "einem Partner versaute Kosenamen gegeben.",
            "in einer Alltagssituation gemerkt, dass ich erregt bin und mich dafür geschämt.",
            "große Schadenfreude verspürt, als ich hörte, dass einem anderen etwas sehr Schlimmes zugestoßen ist.",
            "vor einem Spiegel gesungen.",
            "telefoniert / gechattet, während ich auf dem Klo saß.",
            "Sex auf dem Schreibtisch gehabt.",
            "Sex gehabt, während der Fernseher noch lief.",
            "ein Verkehrsschild überfahren.",
            "eine Beziehung mit zwei Leuten gleichzeitig gehabt.",
            "das Erlebnis gehabt, von der Polizei durchsucht werden zu müssen.",
            "ein Auge auf die Eltern eines Freundes geworfen.",
            "meinem Partner etwas verheimlicht.",
            "meine Unterwäsche irgendwo verloren oder vergessen.",
            "eine Intim-Frisur gehabt, für die ich mich geschämt habe.",
            "erst im Zug bemerkt, dass ich gar kein Ticket gekauft hatte.",
            "erlebt, dass mich ein Freund meines Partners angemacht hat.",
            "Fantasien gehabt, für die ich mich schäme.",
            "so getan als wäre ich betrunken.",
            "Nacktbilder von mir über das Internet verschickt.",
            "aus Versehen im Kino aus dem falschen Glas getrunken oder vom falschen Popkorn gegessen.",
            "etwas deutlich über seinem Wert verkauft.",
            "mit meiner besten Freundin rumgemacht.",
            "Sex im Freien gehabt.",
            "als Jugendlicher vor einem Geschäft gewartet, bis ein Erwachsener kommt, um mir Alkohol zu kaufen.",
            "mit jemandem geschlafen, den ich eine Stunde zuvor noch nicht kannte.",
            "drei Abende hintereinander einen Vollrausch gehabt.",
            "einen Freund/eine Freundin meines Partners abgrundtief gehasst.",
            "eine Glatze gehabt.",
            "im Club einen geblasen bekommen / jemandem einen geblasen.",
            "in einer Vorlesung/Unterrichtsstunde geschlafen.",
            "an meiner Unterwäsche gerochen, nur um zu sehen, ob sie noch frisch ist.",
            "gedacht: “Wenn er/sie mich jetzt anspricht, würde ich noch auf einen Kaffee mit reinkommen”.",
            "Sex in einer Badewanne gehabt.",
            "ein Fahrrad gestohlen.",
            "Sex im Schwimmbad gehabt.",
            "bei diesem Spiel gelogen, weil mein Partner anwesend war.",
            "mit jemandem geschlafen, den ich nicht kannte.",
            "jemandem das Leben gerettet.",
            "einem anderen Autofahrer den Stinkefinger gezeigt.",
            "auf einer Party Sex gehabt.",
            "eine Klausur geschrieben, auf die ich weniger als eine Stunde gelernt hatte.",
            "beim Sex an eine andere Person gedacht.",
            "auf der Toilette telefoniert.",
            "versucht mit einem falschen Geldschein zu bezahlen.",
            "mit zwei oder mehreren Personen an einem Abend rumgerknutscht.",
            "im Bikini Autos gewaschen.",
            "jemandem einen runtergeholt.",
            "mit meinem Partner zusammen erotische Filme oder Bilder angeschaut.",
            "den Wunsch gehabt, ein Mann/eine Frau zu sein.",
            "eine Schlange in meinen Händen gehalten.",
            "Sex gehabt, bei dem ich mich über einen Spiegel im Raum selbst beobachten konnte.",
            "hinter dem Kühlschrank sauber gemacht.",
            "Tierfutter probiert.",
            "den Intimbereich eines Freundes / einer Freundin (gleiches Geschlecht) berührt.",
            "in der Öffentlichkeit in die Hose gepinkelt.",
            "über die Vergrößerung meiner Geschlechtsorgane nachgedacht.",
            "meinen Partner mit der Hand stimuliert.",
            "einen ganzen Tag im Bett verbracht, obwohl ich nicht krank war.",
            "eine wichtige Prüfung nicht bestanden.",
            "länger als 3 Tage nicht geduscht.",
            "versucht meinen Ellbogen zu lecken.",
            "versucht Bilder/Videos auf dem Computer zu verstecken.",
            "gepopelt und es dann gegessen.",
            "einen Haarschnitt gehabt, für den ich mich heute noch schäme.",
            "einen Partner gehabt, für den ich Dinge ausprobiert habe, die ich eigentlich nie machen wollte.",
            "überlegt ein Bordell zu besuchen.",
            "heimlich unter dem Tisch Händchen gehalten.",
            "nachts in einem Fluss gebadet.",
            "einen Partner gehabt, der deutlich mehr Sex als ich wollte.",
            "eine Fernbeziehung gehabt.",
            "so viel getrunken, dass ich den ganzen nächsten Tag im Bett verbringen musste.",
            "die Pille danach genommen.",
            "ausgenutzt, dass jemand total betrunken war.",
            "deutlich mehr Sex gehabt als im Moment.",
            "Bodypainting gemacht.",
            "ins Bett gekotzt.",
            "einen Autounfall mit mehr als 200€ Schaden gehabt.",
            "Sex an einem sehr ungewöhnlichen Ort gehabt.",
            "eine versaute App auf dem Smartphone gehabt.",
            "das Handy meines Partner durchstöbert.",
            "gekifft.",
            "eine Bravo aufgeschlagen, nur um den Dr. Sommer Teil zu lesen.",
            "fantasiert, wie bestimmte Leute wohl beim Sex aussehen.",
            "jemanden auf der Straße gesehen und so getan als hätte ich ihn nicht gesehen.",
            "Sex in einem Schlafsack gehabt.",
            "mich alleine betrunken.",
            "meinen Partner ausgezogen.",
            "beim Sex meinen Freund oder Freundin angekotzt.",
            "Sexspielzeug besessen.",
            "ein Tier gemobbt.",
            "einen Neujahrsvorsatz tatsächlich eingehalten.",
            "meinen eigenen Intimbereich fotografiert.",
            "einen Partner gehabt, dessen Eltern ich nicht leiden konnte.",
            "Sex mit einer Person gehabt mit der ich nicht zusammen war.",
            "in einem Sexshop eingekauft.",
            "mit jemandem geflirtet, mit dem ich keine Beziehung, sondern bloß Sex wollte.",
            "gleichgeschlechtliche Gefühle gehabt.",
            "Sex in einem Aufzug gehabt.",
            "über einen Partnertausch nachgedacht.",
            "davon geträumt beherrscht oder dominiert zu werden.",
            "eine Brille getragen.",
            "eine Beziehung gehabt, die kürzer als 2 Wochen andauerte.",
            "beim Sex oder der Masturbation gestöhnt.",
            "einen Spiegel benutzt, um meine Intimzonen genauer zu betrachten.",
            "etwas besessen, dass ich immer versteckt habe, wenn Freunde kamen.",
            "Natursekt-Spielchen (Urin) ausprobiert.",
            "intime Details über einen meiner Ex-Partner ausgeplaudert.",
            "einen Autounfall gehabt.",
            "bei einem Buch die letzte Zeile zuerst gelesen.",
            "Pornos geschaut und jemand kam rein.",
            "eine Kneipenschlägerei gehabt.",
            "einen Partner gehabt, der deutlich unter meinem Niveau war.",
            "mehr als 42 Stunden ohne Schlaf verbracht.",
            "jemanden zufällig nackt gesehen, den ich nicht nackt hätte sehen sollen.",
            "eine Beziehung zu einer Person gehabt, die maßgeblich auf Sex basiert hat.",
            "nackt ein Auto gefahren.",
            "Oralsex während dem Autofahren gehabt.",
            "an einer Wand gelauscht, um andere beim Sex zu hören.",
            "Sex auf einer Strandliege gehabt.",
            "Handschellen beim Sex benutzt.",
            "während eines Wutanfalls etwas zerstört.",
            "einen Porno geschaut.",
            "Ich habe noch nie Fragen (Teil 15)",
            "meinen Kopf kahl geschoren.",
            "einem Ex-Partner bei der Trennung unangebrachte Beleidigungen an den Kopf geworfen.",
            "mit jemandem geschlafen, den ich verleugnen würde.",
            "eine Hochzeitsrede gehalten.",
            "Selbstgespräche geführt.",
            "eine schlechte Schulnote vor meinen Eltern verheimlicht.",
            "nach dem Sport nicht geduscht.",
            "die E-Mails / Nachrichten meines Partners durchsucht.",
            "Sex mit einer Person gehabt, die nicht meinem Typus entsprach, nur um Sex zu haben.",
            "eine Sucht nach etwas entwickelt.",
            "beim Speed-Dating mitgemacht.",
            "in öffentlichen Verkehrsmitteln absichtlich den Platz gewechselt, um neben einer attraktiven Person zu sitzen.",
            "jemanden an den Füßen stimuliert.",
            "mit dem Schluss machen gewartet, weil ich noch keine andere Person gefunden hatte.",
            "vorgegeben, ich sei homosexuell, um in Ruhe gelassen zu werden.",
            "Pornoheft bei mir zuhause versteckt.",
            "nachts im Gras gelegen und Sternschnuppen beobachtet.",
            "eine Verabredung angenommen, nur um einen Freund/eine Freundin der Person kennenzulernen.",
            "eine Waffe abgefeuert.",
            "24 Stunden am Stück Fernsehen geschaut.",
            "eine Straftat begangen.",
            "beim Oralsex verhütet (wegen Geschlechtskrankheiten).",
            "jemandem “unverbindlichen” Sex angeboten.",
            "mit jemandem geknutscht, dessen Vornamen ich nicht kannte.",
            "Sex gehabt, während andere Personen im Raum waren.",
            "einen ganzen Tag ohne Kleidung verbracht.",
            "Sex im Auto gehabt.",
            "eine vertrauliche SMS/ E-Mail an den falschen Empfänger gesendet.",
            "Sex in einem öffentlichen Schwimmbad / am Strand gehabt.",
            "mehr als einmal Sex unmittelbar hintereinander gehabt.",
            "eine Spam-E-Mail angeklickt, weil ich dachte, dass sie echt ist.",
            "versucht vor der Polizei wegzulaufen.",
            "bei diesem Spiel gelogen.",
            "Peitschen und Ähnliches beim Sex benutzt.",
            "mit jemandem über meine sexuellen Phantasien gesprochen.",
            "ein romantisches Gedicht für meinen Partner vorgetragen.",
            "im Stehen gepinkelt.",
            "versucht den G-Punkt zu finden.",
            "härtere Drogen konsumiert.",
            "darauf gewartet, dass jemand anders den ersten Schritt macht.",
            "in den vergangenen 2 Jahren mehr als 2 Wochen am Stück keinen Alkohol angerührt.",
            "mit anderen Personen zusammen einen Porno gesehen.",
            "meine Eltern beleidigt.",
            "Handschellen am Armgelenk getragen.",
            "hunderte Kilometer zurückgelegt, nur um einen bestimmten Menschen zu sehen.",
            "einen Partner gehabt, der in Sachen Sex nicht so offen war wie ich.",
            "online über Sexspielzeug recherchiert.",
            "eine Zimmerpflanze vertrocknen lassen.",
            "auf jemanden uriniert.",
            "Sex an meinem Arbeitsplatz gehabt.",
            "so viel getrunken, dass ich bei einer Party rausgeworfen wurde.",
            "ein Date mit jemandem gehabt, den ich über das Internet kennengelernt habe."};

}
